name: garmin-mcp-server


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: A job to build the backend Image container
    steps:  
    - name: Checkout code
      uses: actions/checkout@v3
   
    - name: Login to Github Packages
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build image and push LATEST to GitHub Container Registry AMD64
      uses: docker/build-push-action@v6
      with:
          # relative path to the place where source code with Dockerfile is located    
          file: Dockerfile
          context: .
          platforms: linux/amd64
          # Note: tags has to be all lower-case
          tags: | 
            ghcr.io/banzzouille/garmin-mcp-server
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}       

    - name: Clean up dangling images
      run: |
        docker image prune -f  